# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - go-task --list
    silent: true

  build:
    cmds:
      - docker compose build {{.CLI_ARGS}}

  run:
    desc: start service
    cmds:
      - task: dotenv {{.CLI_ARGS}}
      - docker compose up postman
 
  test:
    desc: start service and test it with mock data
    cmds:
      - task: dotenv
      - docker compose up mock -d
      - docker compose up postman
      - docker compose stop mock

  dotenv:
    cmds:
      - cp ./config/{{.ENV_FILE}} .env
    vars:
      ENV_FILE: '{{.CLI_ARGS | default "test" }}'